# Generated by Django 6.0.1 on 2026-01-27 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_forgetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
